---
- hosts: docker
  become: true
  connection: local
  tasks:
  - name: Install Git
    apt:
      pkg: 
      - git
      state: latest
      #update_cache: true
 
  - name: Git Clone Repo
    git:
      repo: https://github.com/LukeBenson/install-scripts
      dest: ./git
 
  - name: Running Docker Script
    script: /home/sheraz_shahid/ansible-tasks/extension/git/docker_install.sh 

- hosts: NGINX
  become: true
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Start NGINX
    service:
      name: nginx
      state: started
